spring.application.name=APICompras
spring.mongodb.host=localhost
spring.mongodb.port=27017
spring.mongodb.database=compras
spring.mongodb.username=${DB_USERNAME}
spring.mongodb.password=${DB_PASSWORD}
spring.mongodb.authentication-database=${DB_AUTHENTICATION}